name: minian
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cvxpy=1.4.2
  - dask=2024.6.2
  - distributed=2024.6.2
  - ecos=2.0.12
  - ffmpeg=6.1.1
  - ffmpeg-python=0.2.0
  - fftw=3.3.10
  - jupyter=1.0.0
  - matplotlib-base=3.8.2
  - natsort=8.4.0
  - netcdf4=1.6.5
  - networkx=3.2.1
  - numba=0.60.0
  - numpy=1.26.4
  - opencv=4.9.0
  - pandas=2.2.0
  - panel=1.3.8
  - param=2.0.1
  - pyfftw=0.15.0
  - scikit-image=0.22.0
  - scikit-learn=1.4.0
  - scipy=1.13.0
  - scs=3.2.4
  - simpleitk=2.3.1
  - sk-video=1.1.10
  - statsmodels=0.14.1
  - tifffile=2024.1.30
  - xarray=2025.07.0
  - zarr=2.18
  - sparse=0.15.0
  - pymetis=2025.2.1
  - rechunker=0.5.0
  - medpy=0.4.0
  - jinja2=3.1.3
  - pip=24.0
  - vispy=0.15.2
  - pyqt=5.15.11